config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'books#index'
  resources :books
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)

    if @book.save
      flash[:success] = 'Book has successfully been created.'
      redirect_to books_path
    else
      flash[:danger] = 'There are some errors.'
      render :new
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :description, :price)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/index.html.erb
<div class="container">
  <div class="jumbotron">
    <h1 class="display-3">Booktopia</h1>
    <p class="lead">A website where you can sell your second hand books.</p>
    <hr class="my-4">
    <p class="lead">
      <%= link_to new_book_path, class: 'btn btn-primary btn-lg' do %>
        Add new book
      <% end %>
    </p>
  </div>

  <% if @books.any? %>
    <table class='table'>
      <thead>
        <tr>
          <th>Title</th>
          <th>Description</th>
          <th>Price</th>
          <th>Date Posted</th>
        </tr>
      </thead>
      <tbody>
        <% @books.each do |book| %>
          <tr>
            <td>
              <%= link_to book.title, book_path(book) %>
            </td>
            <td><%= book.description %></td>
            <td><%= book.price %></td>
            <td><%= book.created_at.strftime('%Y-%m-%d') %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% end %>
</div>

app/views/books/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-6 col-md-offset-3'>
      <%= form_for @book do |f| %>
        <%= render 'shared/forms/text', column_name: :title, placeholder: 'Book title', f: f %>
        <%= render 'shared/forms/text', column_name: :description, placeholder: 'Book title', f: f %>
        <%= render 'shared/forms/text', column_name: :price, placeholder: 'Selling price', type: 'number', f: f %>
        <%= f.submit %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestingLession</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/flash' %>
    <%= render 'shared/header' %>
    <main id="main-content">
      <%= yield %>
    </main>
  </body>
</html>

app/views/shared/_flash.html.erb
<% if flash.any? %>
  <div class="flash-container">
    <% flash.each do |type, message| %>
      <div class="alert alert-#{type}" role="alert">
        <%= message %>
      </div>
    <% end %>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="navbar navbar-light navbar-toggleable-md bd-navbar">
  <nav class="container">
    <div class="d-flex justify-content-between hidden-lg">
      <%= link_to root_path, class: "navbar-brand" do %>
        Booktopia
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bd-main-nav" aria-controls="bd-main-nav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
    <div class="collapse navbar-collapse" id="bd-main-nav">
      <ul class="nav navbar-nav">
        <li class="nav-item active">
          <%= link_to root_path, class: 'nav-item nav-link' do %>
            Booktopia
          <% end %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/forms/_text.html.erb
<% type ||= 'text' %>

<div class="form-group">
  <%= f.label column_name %>
  <%= f.text_field column_name, placeholder: placeholder, type: type, class: "form-control" %>
  <% if f.object.errors[column_name] %>
    <p class="form-text text-muted">
      <%= f.object.errors[column_name].join(', ') %>
    </p>
  <% end %>
</div>